filebeat.inputs:
- type: filestream
  id: dvwa-logs
  enabled: true
  paths:
    - /var/log/dvwa/*.log
  fields:
    log_source: dvwa
  fields_under_root: true
  parsers:
    - ndjson:
        target: ""
        message_key: message
        target_index: 0

output.elasticsearch:
  hosts: ["elk-es:9200"]
  index: "dvwa-logs-%{+yyyy.MM.dd}"

setup.template.name: "dvwa"
setup.template.pattern: "dvwa-*"
