filebeat.inputs:
- type: filestream
  id: dvwa-access
  paths:
    - /var/log/apache2/*.log
  fields:
    log_type: dvwa-apache
  fields_under_root: true

output.elasticsearch:
  hosts: ["elk-es:9200"]
  index: "dvwa-raw-%{+yyyy.MM.dd}"
